# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuingEducationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('required_CE', models.CharField(max_length=200)),
                ('oversight_entity', models.CharField(max_length=200)),
                ('repeat', models.CharField(max_length=200)),
                ('hours', models.CharField(max_length=200)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('top_items_learned', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
