# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuingeducationlog',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
