# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_auto_20170407_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuingeducationlog',
            name='repeat',
            field=models.CharField(choices=[('0.5', 'Biannually'), ('1', 'Yearly'), ('2', 'Every 2 years'), ('3', 'Every 3 years'), ('4', 'Every 4 years'), ('5', 'Every 5 years'), ('Other', 'Other')], max_length=200),
        ),
    ]
