# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_auto_20170419_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuingeducationlog',
            name='top_items_learned',
            field=models.TextField(blank=True),
        ),
    ]
