# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_auto_20170419_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User',
        ),
    ]
