# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_auto_20170419_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
